### ISSUE TITLE
バッグから道具を使うとクラッシュする

### ISSUE THREAD

**Issue by sbkinoko** [sbkinoko/RPGEngine2#319]

**Comment by sbkinoko** [comment]
https://github.com/user-attachments/assets/ceed6d46-a036-47af-b21a-6d707217a776

**Comment by sbkinoko** [comment]
なぜかバッグであることをうまく伝達できてないので確認する

<details>
<summary>
エラー内容
</summary>

 Process: org.example.project, PID: 26909
                                                                                                    java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
                                                                                                    	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
                                                                                                    	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
                                                                                                    	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
                                                                                                    	at java.util.Objects.checkIndex(Objects.java:359)
                                                                                                    	at java.util.ArrayList.get(ArrayList.java:434)
                                                                                                    	at core.repository.player.PlayerStatusRepositoryImpl.getSkill(PlayerStatusRepositoryImpl.kt:166)
                                                                                                    	at gamescreen.menu.item.abstract.target.ItemTargetViewModel.getSkillId(ItemTargetViewModel.kt:36)
                                                                                                    	at gamescreen.menu.item.abstract.target.ItemTargetViewModel.getExplain(ItemTargetViewModel.kt:42)
                                                                                                    	at gamescreen.menu.item.abstract.target.ItemTargetWindowKt.ItemTargetWindow(ItemTargetWindow.kt:33)
                                                                                                    	at gamescreen.menu.item.tool.target.ToolTargetWindowKt.ToolTargetWindow(ToolTargetWindow.kt:13)
                                                                                                    	at gamescreen.menu.MenuScreenKt.MenuScreen(MenuScreen.kt:60)
</details>
